
version: "3.9"

services:
  frontend:
    container_name: cinnamon-frontend-local
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=4173
    ports:
      - "5173:4173"
    restart: unless-stopped